services:
  classicpress:
    image: 'classicpress/classicpress:latest'
    volumes:
      - 'classicpress-files:/var/www/ ahtml'
    environment:
      - SERVICE_FQDN_CLASSICPRESS
      - CLASSICPRESS_DB_HOST=mariadb
      - CLASSICPRESS_DB_USER=$SERVICE_USER_CLASSICPRESS
      - CLASSICPRESS_DB_PASSWORD=$SERVICE_PASSWORD_CLASSICPRESS
      - CLASSICPRESS_DB_NAME=classicpress
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=classicpress
      - MYSQL_USER=$SERVICE_USER_CLASSICPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_CLASSICPRESS
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
